export const surpriseMePrompts = [
  "a hammock shaped like a watermelon",
  "a futuristic skyscraper made entirely of holograms",
  "dancing penguins in tuxedos at a disco in Antarctica",
  "a robot playing piano in a jazz band",
  "a mystical forest with glowing fireflies and floating islands",
  "a close-up photo of a cat wearing sunglasses on a sunny day",
  "a steampunk-style hot air balloon race in the clouds",
  "a superhero sloth saving the day in slow motion",
  "a mountain range shaped like giant ice cream cones",
  "an underwater city with mermaids riding seahorses",
  "a dragon sipping tea in a cozy mountain cave",
  "a carnival carousel with mythical creatures as ride animals",
  "a group of friendly aliens having a picnic on Mars",
  "a time-traveling pirate ship on a rainbow-colored sea",
  "a magical library with books that come to life",
  "a giant robot gardener tending to a field of robotic flowers",
  "a floating island city with hot air balloon transportation",
  "a cybernetic giraffe with neon lights for spots",
  "a secret garden with talking flowers and enchanted pathways",
  "a mysterious doorway leading to a galaxy of floating islands",
  "a parallel universe where animals are the rulers",
  "a whimsical tea party with animals wearing top hats",
  "a cosmic surf competition on waves of stardust",
  "a friendly monster family living in a treehouse",
  "a wizard's workshop filled with magical gadgets",
  "a robot orchestra playing music under the moonlight",
  "an enchanted ice castle with dancing snowflakes",
  "a constellation map that reveals hidden stories",
  "a rainbow-colored zipline through a jungle of candy canes",
  "a surreal garden with upside-down trees and flying fish",
  "a time-traveling train crossing through dimensions",
  "a floating cityscape with clouds made of cotton candy",
  "a space explorer meeting alien friends in a intergalactic cafe",
  "an ancient tree with doors leading to different worlds",
  "a cosmic dance party with planets as disco balls",
  "a giant origami crane soaring through a paper sky",
  "a magical waterfall with liquid rainbow cascading down",
  "a futuristic city where everyone travels on hoverboards",
  "an underwater ballet of graceful jellyfish",
  "a magical carousel that takes riders to dream realms",
  "a robot bee pollinating digital flowers in a virtual garden",
  "a galaxy where constellations tell bedtime stories",
  "a whimsical factory producing clouds in different shapes",
  "a friendly giant snail delivering mail in a fairy-tale land",
];
